=== AndersTrier/ipv6/schema.json
{
  "$id": "https://ipv6-adresse.dk/schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "IPv6-adresse ISP Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "title": "Schema",
      "description": "Pointer to the schema against which this document should be validated.",
      "required": false
    },
    "name": {
      "type": "string",
      "description": "Name of ISP"
    },
    "url": {
      "type": "string",
      "description": "Website of ISP"
    },
    "ipv6": {
      "type": "boolean",
      "description": "Whether the ISP has IPv6-support"
    },
    "partial": {
      "type": "boolean",
      "description": "Whether the ISP has IPv6-support, that only applies to a segmented customer group"
    },
    "comment": {
      "type": "string",
      "description": "Comment on the IPv6 support"
    },
    "private": {
      "type": "boolean",
      "deprecated": true
    },
    "business": {
      "type": "boolean",
      "deprecated": true
    },
    "sources": {
      "type": "array",
      "description": "List of sources",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of source"
          },
          "url": {
            "type": ["string", "null"],
            "description": "Website of source"
          },
          "date": {
            "type": "string",
            "description": "Date of source - must be in YYYY-MM-DD format"
          }
        }
      }
    }
  }
}

=== AndersTrier/ipv6/data/skywire.json
{
  "name": "Skywire",
  "url": "http://www.skywire.dk",
  "ipv6": false,
  "comment": "Vi har planer om at udbyde det, men har på nuværende tidspunkt ingen tidshorisont for det.",
  "partial": false,
  "sources": [
    { "date": "2018-10-29", "name": "ISP", "url": null },
    { "date": "2015-11-30", "name": "ISP", "url": null }
  ]
}

=== AndersTrier/ipv6/data/stofa.json
{
  "$schema": "./../schema.json",
  "name": "Stofa - en del af Norlys",
  "url": "https://stofa.dk",
  "ipv6": true,
  "comment": "Erhvervskunder og privatkunder på fiber har mulighed for IPv6, en del forbrugere aktiveret pr. default. IPv6 på COAX forbindelser understøttes ikke af TDC. xDSL (kobber) ukendt",
  "partial": true,
  "sources": [
    {
      "date": "2022-08-18",
      "name": "ISP",
      "url": null
    },
    {
      "date": "2021-12-10",
      "name": "ISP",
      "url": null
    }
  ]
}

=== AndersTrier/ipv6/data/telmore.json
{
  "$schema": "./../schema.json",
  "name": "Telmore",
  "url": "https://www.telmore.dk",
  "ipv6": true,
  "comment": "Du har både en IPv4 og en IPv6-adresse, i tilfælde af, at du kommer i kontakt med netværksudstyr, der bruger en IPv6-adresse",
  "partial": false,
  "sources": [{"date": "2019-6-27", "name": "Tweet", "url": "https://twitter.com/telmore/status/1144160756075831297"}]
}

=== AndersTrier/ipv6/data/sef-fiber.json
{
  "$schema": "./../schema.json",
  "name": "SEF FIBER",
  "url": "https://sef.dk",
  "ipv6": true,
  "comment": "Se Stofa (Kommentar: SEF Fiber har Stofa som udbyder og det er dem der varetager al drift af fibernettet. Det er derfor Stofa du bør kontakte for at få svar på dit spørgsmål.)",
  "partial": true,
  "private": true,
  "sources": [{ "date": "2021-02-20", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/fastspeed.json
{
  "name": "Fastspeed (og JETNET)",
  "url": "https://fastspeed.dk",
  "ipv6": true,
  "comment": "Faspeed understøtter IPv6 (undtaget Aura's fibernet). IPv6 på COAX forbindelser understøttes ikke af TDC.",
  "partial": true,
  "private": true,
  "sources": [{ "date": "2020-04-28", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/kazoom.json
{
  "name": "KAZOOM",
  "url": "https://www.kazoom.dk",
  "ipv6": false,
  "comment": "IPv6 adresser er ikke noget, KAZOOM har mulighed for at tildele",
  "partial": false,
  "sources": [
    {
      "date": "2020-12-30",
      "name": "ISP",
      "url": "https://www.kazoom.dk/sporgsmal-og-svar-opsaetning-og-installation/kan-jeg-fa-en-fast-ip-adresse"
    }
  ]
}

=== AndersTrier/ipv6/data/dansk-kabel tv.json
{
  "$schema": "./../schema.json",
  "name": "Dansk Kabel TV",
  "url": "https://www.danskkabeltv.dk",
  "ipv6": false,
  "comment": "De kan på nuværende tidspunkt, ikke oplyse om de kommer til at tilbyde IPv6, på et senere tidspunkt.",
  "partial": false,
  "sources": [{ "date": "2023-04-20", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/zen-systems.json
{
  "name": "Zen Systems (ejet af GlobalConnect)",
  "url": "https://www.globalconnect.dk",
  "ipv6": true,
  "comment": "Vi er fuldt IPv6 klar og har allerede nogle kunder som k√∏rer dual stack. Leverer kun til erhvervskunder.",
  "partial": false,
  "business": true,
  "sources": [{ "date": "2013-09-30", "name": "ISP", "url": null }]
}
