=== AndersTrier/ipv6/schema.json
{
  "$id": "https://ipv6-adresse.dk/schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "IPv6-adresse ISP Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "title": "Schema",
      "description": "Pointer to the schema against which this document should be validated.",
      "required": false
    },
    "name": {
      "type": "string",
      "description": "Name of ISP"
    },
    "url": {
      "type": "string",
      "description": "Website of ISP"
    },
    "ipv6": {
      "type": "boolean",
      "description": "Whether the ISP has IPv6-support"
    },
    "partial": {
      "type": "boolean",
      "description": "Whether the ISP has IPv6-support, that only applies to a segmented customer group"
    },
    "comment": {
      "type": "string",
      "description": "Comment on the IPv6 support"
    },
    "private": {
      "type": "boolean",
      "deprecated": true
    },
    "business": {
      "type": "boolean",
      "deprecated": true
    },
    "sources": {
      "type": "array",
      "description": "List of sources",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of source"
          },
          "url": {
            "type": ["string", "null"],
            "description": "Website of source"
          },
          "date": {
            "type": "string",
            "description": "Date of source - must be in YYYY-MM-DD format"
          }
        }
      }
    }
  }
}

=== AndersTrier/ipv6/data/eniig.json
{
  "$schema": "./../schema.json",
  "name": "Eniig",
  "url": "https://eniig.dk",
  "ipv6": true,
  "comment": "Tilbyder Erhvervs Prof kunder IPv6. Vi har ikke endnu fastlagt nogle planer om at overgå til IPv6.Det vil komme på et tidspunkt, men det forventes ikke at ske inden 2022.",
  "partial": true,
  "sources": [{ "date": "2020-07-06", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/kviknet.json
{
  "$schema": "./../schema.json",
  "name": "Kviknet",
  "url": "https://www.kviknet.dk",
  "ipv6": true,
  "comment": "Kviknet understøtter IPv6. IPv6 på COAX forbindelser understøttes ikke af TDC.",
  "partial": true,
  "private": true,
  "sources": [
    {
      "date": "2023-12-22",
      "name": "Kviknet FAQ - Internet Optsætning",
      "url": "https://web.archive.org/web/20221003090412/https://support.kviknet.dk/hc/da/articles/6495304559249-Internet-ops%C3%A6tning"
    },
    {
      "date": "2023-12-22",
      "name": "Kviknet FAQ - DHCPv6 IAID Issues",
      "url": "https://web.archive.org/web/20220813145436/https://support.kviknet.dk/hc/da/articles/7972272930193-DHCPv6-IAID-Issues"
    },
    {
      "date": "2023-12-22",
      "name": "Kviknet FAQ - Statisk DUID Værdi",
      "url": "https://web.archive.org/web/20221003075730/https://support.kviknet.dk/hc/da/articles/6650187045265-Statisk-DUID-v%C3%A6rdi"
    },
    {
      "date": "2021-11-17",
      "name": "Email",
      "url": "https://github.com/emilstahl/ipv6/issues/48"
    },
    {
      "date": "2020-10-01",
      "name": "ISP",
      "url": "https://www.kviknet.dk/produktinfo/fiber_norlys"
    },
    {
      "date": "2016-10-28",
      "name": "ISP",
      "url": "https://v2.dk/1011318"
    }
  ]
}

=== AndersTrier/ipv6/data/telenor.json
{
  "$schema": "./../schema.json",
  "name": "Telenor",
  "url": "https://www.telenor.dk",
  "ipv6": false,
  "comment": "Der er ikke specifikke planer for implementering af IPv6 i øjeblikket.",
  "partial": true,
  "sources": [
    {
      "date": "2023-04-20",
      "name": "FB Tråd",
      "url": "https://www.facebook.com/telenordanmark/posts/492241444121526"
    },
    {
      "date": "2020-05-27",
      "name": "Tweet",
      "url": "https://twitter.com/Dpj_DBB/status/1265623450166734849"
    }
  ]
}

=== AndersTrier/ipv6/data/aura.json
{
  "$schema": "./../schema.json",
  "name": "AURA",
  "url": "https://www.aura.dk",
  "ipv6": false,
  "comment": "…i forhold til dit spørgsmål så har vi ikke planer om at få IPV6 til privat kunder da vi ikke har nok kunder i vores område til at det kan betale sig",
  "partial": false,
  "sources": [
    { "date": "2024-02-01", "name": "ISP", "url": null },
    { "date": "2018-10-26", "name": "ISP", "url": null },
    { "date": "2016-12-21", "name": "ISP", "url": null }
  ]
}

=== AndersTrier/ipv6/data/bolignet-aarhus.json
{
  "$schema": "./../schema.json",
  "name": "Bolignet-Aarhus",
  "url": "http://bolignet-aarhus.dk",
  "ipv6": false,
  "comment": "Vi tester IPv6 i backbone. Det tilbydes ikke til nogle kunder på nuværende tidspunkt. Vi har ingen umiddelbare planer for udrulning til private.\n ",
  "partial": true,
  "private": true,
  "sources": [{ "date": "2017-04-21", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/energi-fyn.json
{"name":"Energi Fyn","url":"https://www.energifyn.dk/privat","ipv6":true,"comment":"Understøtter IPv6 i vores Erhverv Pro-produkt. Der går nok nogle år endnu før vi tilbyder til privatkunder.","partial":true,"sources":[{"date":"2016-05-27","name":"PDF","url":"https://www.energifyn.dk/-/media/energifyndk/ny-struktur/dokumenter/erhverv/fibernet/erhverv-fibernet_produktspecifikation-erhverv-pro_18-10-2017.ashx"}]}

=== AndersTrier/ipv6/data/norlys.json
{
  "$schema": "./../schema.json",
  "name": "Norlys",
  "url": "https://www.norlys.dk",
  "ipv6": true,
  "comment": "Erhvervskunder og privatkunder på fiber har mulighed for IPv6, en del forbrugere aktiveret pr. default. IPv6 på COAX forbindelser understøttes ikke af TDC. xDSL (kobber) ukendt",
  "partial": true,
  "private": true,
  "sources": [{ "date": "2023-09-20", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/bolignet.json
{"name":"bolig:net","url":"https://www.bolignet.dk","ipv6":false,"comment":"Har omlagt netværk April 2021, fjernet IPv6 for en stor andel af kunderne. Forventer der vil gå måneder.","partial":false,"sources":[{"date":"2021-04-14","name":"Tweet","url":"https://twitter.com/kramse/status/1382277899684827138"}]}
