=== AndersTrier/ipv6/schema.json
{
  "$id": "https://ipv6-adresse.dk/schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "IPv6-adresse ISP Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "title": "Schema",
      "description": "Pointer to the schema against which this document should be validated.",
      "required": false
    },
    "name": {
      "type": "string",
      "description": "Name of ISP"
    },
    "url": {
      "type": "string",
      "description": "Website of ISP"
    },
    "ipv6": {
      "type": "boolean",
      "description": "Whether the ISP has IPv6-support"
    },
    "partial": {
      "type": "boolean",
      "description": "Whether the ISP has IPv6-support, that only applies to a segmented customer group"
    },
    "comment": {
      "type": "string",
      "description": "Comment on the IPv6 support"
    },
    "private": {
      "type": "boolean",
      "deprecated": true
    },
    "business": {
      "type": "boolean",
      "deprecated": true
    },
    "sources": {
      "type": "array",
      "description": "List of sources",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of source"
          },
          "url": {
            "type": ["string", "null"],
            "description": "Website of source"
          },
          "date": {
            "type": "string",
            "description": "Date of source - must be in YYYY-MM-DD format"
          }
        }
      }
    }
  }
}

=== AndersTrier/ipv6/data/parknet.json
{
  "$schema": "./../schema.json",
  "name": "Parknet",
  "url": "https://parknet.dk",
  "ipv6": false,
  "comment": "Det er noget vi arbejder hen imod. Jeg har dog ingen dato for hvorn√•r det vil blive rullet ud.",
  "partial": false,
  "sources": [{ "date": "2023-06-09", "name": "ISP (Email)", "url": null }]
}

=== AndersTrier/ipv6/data/boxer.json
{
  "name": "Boxer",
  "url": "https://www.boxertv.dk",
  "ipv6": false,
  "comment": "For nu har TDC rigeligt IP-adresser. Såfremt TDC Privat beslutter at indføre IPv6, så kommer Boxer Bredbånd også til at få det.",
  "partial": false,
  "private": true,
  "sources": [{ "date": "2016-01-25", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/telia.json
{
  "$schema": "./../schema.json",
  "name": "Telia",
  "url": "https://www.telia.dk/privat/",
  "ipv6": true,
  "comment": "Leverer IPv6. Ikke alle routere er underst√∏ttet.",
  "partial": true,
  "sources": [
    {
      "date": "2015-03-11",
      "name": "Tweet",
      "url": "https://twitter.com/TeliaDanmark/status/626304483937624064"
    }
  ]
}

=== AndersTrier/ipv6/data/hiper.json
{"name":"Hiper","url":"https://www.hiper.dk","ipv6":true,"comment":"Vil tildeler IPv6 til alle kunder på både xDSL og fiber. Vi håber også at kunne komme til at gøre det på coax inden for overskuelig fremtid, men det er vi desværre ikke selv herre over grundet platformens indretning.","partial":true,"private":true,"sources":[{"date":"2015-12-16","name":"ISP","url":null}]}

=== AndersTrier/ipv6/data/tdc-erhverv.json
{
  "name": "TDC Erhverv",
  "url": "https://tdc.dk",
  "ipv6": true,
  "comment": "Leverer IPv6 til erhverv på professionelle fiberløsninger.",
  "partial": true,
  "business": true,
  "sources": [
    {
      "date": "2016-04-06",
      "name": "Tweet",
      "url": "https://twitter.com/ikjensen/status/575569892990193664"
    }
  ]
}

=== AndersTrier/ipv6/data/kalundborgegnens-antennelaug.json
{
  "$schema": "./../schema.json",
  "name": "Kalundborgegnens Antennelaug",
  "url": "https://ka-net.dk/",
  "ipv6": true,
  "comment": "Kalundborgegnens Antennelaug k√∏rer IPv6 Dual stack helt ud til slutbrugeren.",
  "partial": false,
  "private": true,
  "sources": [{ "date": "2017-06-06", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/asom-net.json
{
  "$schema": "./../schema.json",
  "name": "ASOM-Net",
  "url": "https://asom-net.dk",
  "ipv6": true,
  "comment": "ASOM-Net tilbyder dual-stack IPv6 med /48 prefix-delegation hos alle kunder. Leverer kun til private.",
  "partial": false,
  "private": true,
  "sources": [{ "date": "2022-09-09", "name": "ISP", "url": null }]
}

=== AndersTrier/ipv6/data/altibox.json
{
  "$schema": "./../schema.json",
  "name": "Altibox",
  "url": "https://www.altibox.dk",
  "ipv6": false,
  "comment": "Vi tilbyder ikke på nuværende tidspunkt statisk tildeling af IPv6 prefix/adresser.",
  "partial": true,
  "sources": [{ "date": "2023-11-06", "name": "ISP (Email)", "url": null }]
}
